const crossExchangeOrderSubmissionEnabled =
  process.env.ENABLE_CROSS_EXCHANGE_ORDER_SUBMISSION === "true";
const spotPerpCarryOrderSubmissionEnabled =
  process.env.ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION === "true";

module.exports = {
  apps: [
    {
      name: "dry-run-manager",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-manager.out.log",
      error_file: "./var/log/pm2/dry-run-manager.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
        DRY_RUN_EXECUTION_MODE: "paper",
        DRY_RUN_MARKETS: "KRW-BTC",
        DRY_RUN_ENTRY_PROFILE: "v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1_book_confirm3",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/dry-run-btc-confirm3-service",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/paper-sessions-btc-confirm3",
      },
    },
    {
      name: "dry-run-btc-trend-manager",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-btc-trend-manager.out.log",
      error_file: "./var/log/pm2/dry-run-btc-trend-manager.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
        DRY_RUN_EXECUTION_MODE: "paper",
        DRY_RUN_MARKETS: "KRW-BTC",
        DRY_RUN_ENTRY_PROFILE: "btc_trend_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1_book_confirm3",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/dry-run-btc-trend-service",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/paper-sessions-btc-trend",
      },
    },
    {
      name: "dry-run-btc-trend-hold-manager",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-btc-trend-hold-manager.out.log",
      error_file: "./var/log/pm2/dry-run-btc-trend-hold-manager.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
        DRY_RUN_EXECUTION_MODE: "paper",
        DRY_RUN_MARKETS: "KRW-BTC",
        DRY_RUN_ENTRY_PROFILE: "btc_trend_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1_book_confirm3_trend_hold",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/dry-run-btc-trend-hold-service",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/paper-sessions-btc-trend-hold",
      },
    },
    {
      name: "dry-run-btc-trend-hold-guarded-manager",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-btc-trend-hold-guarded-manager.out.log",
      error_file: "./var/log/pm2/dry-run-btc-trend-hold-guarded-manager.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
        DRY_RUN_EXECUTION_MODE: "paper",
        DRY_RUN_MARKETS: "KRW-BTC",
        DRY_RUN_ENTRY_PROFILE: "btc_trend_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1_book_confirm3_trend_hold_guarded",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/dry-run-btc-trend-hold-guarded-service",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/paper-sessions-btc-trend-hold-guarded",
      },
    },
    {
      name: "dry-run-btc-trend-ret1-turnover-cap-manager",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-btc-trend-ret1-turnover-cap-manager.out.log",
      error_file: "./var/log/pm2/dry-run-btc-trend-ret1-turnover-cap-manager.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
        DRY_RUN_EXECUTION_MODE: "paper",
        DRY_RUN_MARKETS: "KRW-BTC",
        DRY_RUN_ENTRY_PROFILE: "btc_trend_ret1_turnover_cap_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1_book_confirm3",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/dry-run-btc-trend-ret1-turnover-cap-service",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/paper-sessions-btc-trend-ret1-turnover-cap",
      },
    },
    {
      name: "live-btc-manager",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-btc-manager.out.log",
      error_file: "./var/log/pm2/live-btc-manager.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        LIVE_READINESS_APPROVED: process.env.LIVE_READINESS_APPROVED ?? "false",
        LIVE_TRADING_FEE_SCHEDULE_CONFIRMED: process.env.LIVE_TRADING_FEE_SCHEDULE_CONFIRMED ?? "false",
        LIVE_TRADING_FEE_ROUND_TRIP_BPS: process.env.LIVE_TRADING_FEE_ROUND_TRIP_BPS ?? "50",
        LIVE_READINESS_MAX_AGE_MS: "900000",
        LIVE_READINESS_SUMMARY_PATH: "var/reports/btc-240m-momentum-readiness-latest-refresh.json",
        LIVE_GOAL_STATUS_PATH: "var/reports/live-goal-status-20260513-current.json",
        DRY_RUN_EXECUTION_MODE: "live",
        DRY_RUN_MARKETS: "KRW-BTC",
        DRY_RUN_ENTRY_PROFILE: "btc_240m_momentum_public_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1_book_confirm3",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/live-btc-240m-momentum-service",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/live-sessions-btc-240m-momentum",
      },
    },
    {
      name: "live-btc-min75-manager",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 5000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-btc-min75-manager.out.log",
      error_file: "./var/log/pm2/live-btc-min75-manager.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        LIVE_READINESS_APPROVED: process.env.LIVE_READINESS_APPROVED ?? "false",
        LIVE_TRADING_FEE_SCHEDULE_CONFIRMED: process.env.LIVE_TRADING_FEE_SCHEDULE_CONFIRMED ?? "false",
        LIVE_TRADING_FEE_ROUND_TRIP_BPS: process.env.LIVE_TRADING_FEE_ROUND_TRIP_BPS ?? "50",
        LIVE_READINESS_MAX_AGE_MS: "900000",
        LIVE_READINESS_SUMMARY_PATH: "var/reports/btc-240m-momentum-min75-readiness-latest-refresh.json",
        LIVE_GOAL_STATUS_PATH: "var/reports/live-goal-status-20260513-current.json",
        DRY_RUN_EXECUTION_MODE: "live",
        DRY_RUN_MARKETS: "KRW-BTC",
        DRY_RUN_ENTRY_PROFILE: "btc_240m_momentum_min75_candidate_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1_book_confirm3",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/live-btc-240m-momentum-min75-service",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/live-sessions-btc-240m-momentum-min75",
      },
    },
    {
      name: "dry-run-btc-240m-momentum-observer",
      cwd: __dirname,
      script: "dist/src/cli/refresh-btc-240m-momentum-readiness.js",
      args: "--live-execution-path-ready --execute-exit-when-due",
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-btc-240m-momentum-observer.out.log",
      error_file: "./var/log/pm2/dry-run-btc-240m-momentum-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "live-cross-exchange-relative-value",
      cwd: __dirname,
      script: "dist/src/cli/run-cross-exchange-relative-value-live.js",
      args: [
        "--readiness-report",
        "var/reports/cross-exchange-live-readiness-btc-binance-50k-60m-usdtkrw-orderbook-latest.json",
        "--output",
        "var/reports/cross-exchange-live-execution-latest.json",
        "--live-goal-status",
        "var/reports/live-goal-status-20260513-current.json",
        ...(crossExchangeOrderSubmissionEnabled ? ["--submit-once"] : []),
      ],
      interpreter: "node",
      autorestart: false,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-cross-exchange-relative-value.out.log",
      error_file: "./var/log/pm2/live-cross-exchange-relative-value.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        ENABLE_CROSS_EXCHANGE_LIVE_EXECUTION:
          process.env.ENABLE_CROSS_EXCHANGE_LIVE_EXECUTION ?? "false",
        ENABLE_CROSS_EXCHANGE_ORDER_SUBMISSION:
          process.env.ENABLE_CROSS_EXCHANGE_ORDER_SUBMISSION ?? "false",
        LIVE_READINESS_SUMMARY_PATH: "var/reports/cross-exchange-live-readiness-btc-binance-50k-60m-usdtkrw-orderbook-latest.json",
      },
    },
    {
      name: "live-spot-perp-carry",
      cwd: __dirname,
      script: "dist/src/cli/run-spot-perp-carry-live.js",
      args: [
        "--readiness-report",
        "var/reports/spot-perp-carry-pieverse-edu-live-readiness-latest.json",
        "--carry-report",
        "var/reports/spot-perp-carry-pieverse-edu-72h-latest.json",
        "--market",
        "KRW-PIEVERSE",
        "--output",
        "var/reports/spot-perp-carry-live-execution-latest.json",
        "--live-goal-status",
        "var/reports/live-goal-status-20260513-current.json",
        "--require-live-ready",
        ...(spotPerpCarryOrderSubmissionEnabled ? ["--submit-once"] : []),
      ],
      interpreter: "node",
      autorestart: false,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-spot-perp-carry.out.log",
      error_file: "./var/log/pm2/live-spot-perp-carry.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION:
          process.env.ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION:
          process.env.ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION ?? "false",
        LIVE_READINESS_SUMMARY_PATH:
          "var/reports/spot-perp-carry-pieverse-edu-live-readiness-latest.json",
      },
    },
    {
      name: "live-spot-perp-carry-pieverse",
      cwd: __dirname,
      script: "dist/src/cli/run-spot-perp-carry-live.js",
      args: [
        "--readiness-report",
        "var/reports/spot-perp-carry-pieverse-live-readiness-latest.json",
        "--carry-report",
        "var/reports/spot-perp-carry-pieverse-72h-latest.json",
        "--market",
        "KRW-PIEVERSE",
        "--output",
        "var/reports/spot-perp-carry-pieverse-live-execution-latest.json",
        "--live-goal-status",
        "var/reports/live-goal-status-20260513-current.json",
        "--require-live-ready",
        ...(spotPerpCarryOrderSubmissionEnabled ? ["--submit-once"] : []),
      ],
      interpreter: "node",
      autorestart: false,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-spot-perp-carry-pieverse.out.log",
      error_file: "./var/log/pm2/live-spot-perp-carry-pieverse.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION:
          process.env.ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION:
          process.env.ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION ?? "false",
        LIVE_READINESS_SUMMARY_PATH:
          "var/reports/spot-perp-carry-pieverse-live-readiness-latest.json",
      },
    },
    {
      name: "live-spot-perp-carry-edu",
      cwd: __dirname,
      script: "dist/src/cli/run-spot-perp-carry-live.js",
      args: [
        "--readiness-report",
        "var/reports/spot-perp-carry-edu-live-readiness-latest.json",
        "--carry-report",
        "var/reports/spot-perp-carry-edu-72h-latest.json",
        "--market",
        "KRW-EDU",
        "--output",
        "var/reports/spot-perp-carry-edu-live-execution-latest.json",
        "--live-goal-status",
        "var/reports/live-goal-status-20260513-current.json",
        "--require-live-ready",
        ...(spotPerpCarryOrderSubmissionEnabled ? ["--submit-once"] : []),
      ],
      interpreter: "node",
      autorestart: false,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-spot-perp-carry-edu.out.log",
      error_file: "./var/log/pm2/live-spot-perp-carry-edu.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION:
          process.env.ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION:
          process.env.ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION ?? "false",
        LIVE_READINESS_SUMMARY_PATH:
          "var/reports/spot-perp-carry-edu-live-readiness-latest.json",
      },
    },
    {
      name: "live-spot-perp-carry-cys",
      cwd: __dirname,
      script: "dist/src/cli/run-spot-perp-carry-live.js",
      args: [
        "--readiness-report",
        "var/reports/spot-perp-carry-cys-live-readiness-latest.json",
        "--carry-report",
        "var/reports/spot-perp-carry-cys-72h-latest.json",
        "--market",
        "KRW-CYS",
        "--output",
        "var/reports/spot-perp-carry-cys-live-execution-latest.json",
        "--live-goal-status",
        "var/reports/live-goal-status-20260513-current.json",
        "--require-live-ready",
        ...(spotPerpCarryOrderSubmissionEnabled ? ["--submit-once"] : []),
      ],
      interpreter: "node",
      autorestart: false,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-spot-perp-carry-cys.out.log",
      error_file: "./var/log/pm2/live-spot-perp-carry-cys.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION:
          process.env.ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION:
          process.env.ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION ?? "false",
        LIVE_READINESS_SUMMARY_PATH:
          "var/reports/spot-perp-carry-cys-live-readiness-latest.json",
      },
    },
    {
      name: "live-spot-perp-carry-aztec",
      cwd: __dirname,
      script: "dist/src/cli/run-spot-perp-carry-live.js",
      args: [
        "--readiness-report",
        "var/reports/spot-perp-carry-aztec-live-readiness-latest.json",
        "--carry-report",
        "var/reports/spot-perp-carry-aztec-72h-latest.json",
        "--market",
        "KRW-AZTEC",
        "--output",
        "var/reports/spot-perp-carry-aztec-live-execution-latest.json",
        "--live-goal-status",
        "var/reports/live-goal-status-20260513-current.json",
        "--require-live-ready",
        ...(spotPerpCarryOrderSubmissionEnabled ? ["--submit-once"] : []),
      ],
      interpreter: "node",
      autorestart: false,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-spot-perp-carry-aztec.out.log",
      error_file: "./var/log/pm2/live-spot-perp-carry-aztec.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION:
          process.env.ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION:
          process.env.ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION ?? "false",
        LIVE_READINESS_SUMMARY_PATH:
          "var/reports/spot-perp-carry-aztec-live-readiness-latest.json",
      },
    },
    {
      name: "live-spot-perp-carry-nil",
      cwd: __dirname,
      script: "dist/src/cli/run-spot-perp-carry-live.js",
      args: [
        "--readiness-report",
        "var/reports/spot-perp-carry-nil-live-readiness-latest.json",
        "--carry-report",
        "var/reports/spot-perp-carry-nil-72h-latest.json",
        "--market",
        "KRW-NIL",
        "--output",
        "var/reports/spot-perp-carry-nil-live-execution-latest.json",
        "--live-goal-status",
        "var/reports/live-goal-status-20260513-current.json",
        "--require-live-ready",
        ...(spotPerpCarryOrderSubmissionEnabled ? ["--submit-once"] : []),
      ],
      interpreter: "node",
      autorestart: false,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-spot-perp-carry-nil.out.log",
      error_file: "./var/log/pm2/live-spot-perp-carry-nil.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION:
          process.env.ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION:
          process.env.ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION ?? "false",
        LIVE_READINESS_SUMMARY_PATH:
          "var/reports/spot-perp-carry-nil-live-readiness-latest.json",
      },
    },
    {
      name: "live-spot-perp-carry-akt",
      cwd: __dirname,
      script: "dist/src/cli/run-spot-perp-carry-live.js",
      args: [
        "--readiness-report",
        "var/reports/spot-perp-carry-akt-live-readiness-latest.json",
        "--carry-report",
        "var/reports/spot-perp-carry-akt-72h-latest.json",
        "--market",
        "KRW-AKT",
        "--output",
        "var/reports/spot-perp-carry-akt-live-execution-latest.json",
        "--live-goal-status",
        "var/reports/live-goal-status-20260513-current.json",
        "--require-live-ready",
        ...(spotPerpCarryOrderSubmissionEnabled ? ["--submit-once"] : []),
      ],
      interpreter: "node",
      autorestart: false,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/live-spot-perp-carry-akt.out.log",
      error_file: "./var/log/pm2/live-spot-perp-carry-akt.err.log",
      env: {
        TRADING_MODE: "live",
        ENABLE_LIVE_EXECUTION: process.env.ENABLE_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION:
          process.env.ENABLE_SPOT_PERP_CARRY_LIVE_EXECUTION ?? "false",
        ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION:
          process.env.ENABLE_SPOT_PERP_CARRY_ORDER_SUBMISSION ?? "false",
        LIVE_READINESS_SUMMARY_PATH:
          "var/reports/spot-perp-carry-akt-live-readiness-latest.json",
      },
    },
    {
      name: "dry-run-btc-240m-momentum-min75-observer",
      cwd: __dirname,
      script: "dist/src/cli/refresh-btc-240m-momentum-readiness.js",
      args: [
        "--benchmark",
        "var/reports/btc-240m-momentum-min75-p70-benchmark-fee20-20260512.json",
        "--stress-benchmark",
        "var/reports/btc-240m-momentum-min75-p70-benchmark-fee50-20260513.json",
        "--paper-report",
        "var/paper-sessions-btc-240m-momentum-min75-observation/date=2026-05-12/session=paper-btc_240m_momentum_min75_candidate_v1-2026-05-12T110000000Z/report.json",
        "--paper-observation",
        "var/reports/btc-240m-momentum-min75-paper-observation-20260512.json",
        "--paper-reports-dir",
        "var/paper-sessions-btc-240m-momentum-min75-observation",
        "--artifact-prefix",
        "btc-240m-momentum-min75",
        "--min-return-bps",
        "75",
        "--risk-threshold",
        "435.9906664851208",
        "--live-execution-path-ready",
        "--execute-exit-when-due",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-btc-240m-momentum-min75-observer.out.log",
      error_file: "./var/log/pm2/dry-run-btc-240m-momentum-min75-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-krw-h-60m-momentum-refresh-observer",
      cwd: __dirname,
      script: "dist/src/cli/refresh-bithumb-replacement-time-series-readiness.js",
      args: [
        "--scan",
        "var/reports/current-executable-27-60m-momentum-fee35-500k-20260513-autocheck.json",
        "--market",
        "KRW-H",
        "--signal-mode",
        "momentum",
        "--unit-minutes",
        "60",
        "--lookback-bars",
        "168",
        "--hold-bars",
        "24",
        "--min-return-bps",
        "0",
        "--min-drop-bps",
        "50",
        "--risk-filter",
        "range24_below_p70",
        "--risk-threshold",
        "2065.7276995305174",
        "--notional-krw",
        "500000",
        "--expected-median-edge-bps",
        "138.73015874",
        "--observation-output",
        "var/reports/h-60m-momentum-top-forward-observation-latest.json",
        "--paper-observation-output",
        "var/reports/h-60m-momentum-paper-observation-latest.json",
        "--position-audit-output",
        "var/reports/h-60m-momentum-position-audit-latest.json",
        "--readiness-output",
        "var/reports/h-60m-momentum-replacement-readiness-latest.json",
        "--paper-reports-dir",
        "var/paper-sessions-krw-h-60m-momentum-observation",
        "--strategy-id",
        "krw_h_60m_momentum_top_candidate_v1",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-krw-h-60m-momentum-refresh-observer.out.log",
      error_file: "./var/log/pm2/dry-run-krw-h-60m-momentum-refresh-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-krw-h-60m-momentum-managed-paper",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-krw-h-60m-momentum-managed-paper.out.log",
      error_file: "./var/log/pm2/dry-run-krw-h-60m-momentum-managed-paper.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
        DRY_RUN_EXECUTION_MODE: "paper",
        DRY_RUN_MARKETS: "KRW-H",
        DRY_RUN_ENTRY_PROFILE: "krw_h_60m_momentum_top_candidate_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/dry-run-krw-h-60m-momentum-managed-paper",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/paper-sessions-krw-h-60m-momentum-managed",
      },
    },
    {
      name: "dry-run-krw-h-60m-momentum-managed-return-observer",
      cwd: __dirname,
      script: "dist/src/cli/summarize-dry-run-returns.js",
      args: [
        "--reports-root",
        "var/paper-sessions-krw-h-60m-momentum-managed",
        "--cycles-path",
        "var/log/dry-run-krw-h-60m-momentum-managed-paper/cycles.ndjson",
        "--output",
        "var/reports/krw-h-60m-momentum-managed-paper-return-summary-latest.json",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-krw-h-60m-momentum-managed-return-observer.out.log",
      error_file: "./var/log/pm2/dry-run-krw-h-60m-momentum-managed-return-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-stable-60m-reversal-refresh-observer",
      cwd: __dirname,
      script: "dist/src/cli/refresh-bithumb-replacement-time-series-readiness.js",
      args: [
        "--scan",
        "var/reports/krw-stable-public-60m-reversal-scan-fee20-5000-20260513.json",
        "--market",
        "KRW-STABLE",
        "--signal-mode",
        "reversal",
        "--unit-minutes",
        "60",
        "--lookback-bars",
        "24",
        "--hold-bars",
        "24",
        "--min-return-bps",
        "50",
        "--min-drop-bps",
        "50",
        "--risk-filter",
        "none",
        "--notional-krw",
        "500000",
        "--expected-median-edge-bps",
        "39.37016",
        "--observation-output",
        "var/reports/stable-60m-reversal-top-forward-observation-latest.json",
        "--paper-observation-output",
        "var/reports/stable-60m-reversal-paper-observation-latest.json",
        "--position-audit-output",
        "var/reports/stable-60m-reversal-position-audit-latest.json",
        "--readiness-output",
        "var/reports/stable-60m-reversal-replacement-readiness-latest.json",
        "--paper-reports-dir",
        "var/paper-sessions-stable-60m-reversal-observation",
        "--strategy-id",
        "stable_60m_reversal_candidate_v1",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-stable-60m-reversal-refresh-observer.out.log",
      error_file: "./var/log/pm2/dry-run-stable-60m-reversal-refresh-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-stable-60m-reversal-managed-paper",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-stable-60m-reversal-managed-paper.out.log",
      error_file: "./var/log/pm2/dry-run-stable-60m-reversal-managed-paper.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
        DRY_RUN_EXECUTION_MODE: "paper",
        DRY_RUN_MARKETS: "KRW-STABLE",
        DRY_RUN_ENTRY_PROFILE: "stable_60m_reversal_candidate_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/dry-run-stable-60m-reversal-managed-paper",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/paper-sessions-stable-60m-reversal-managed",
      },
    },
    {
      name: "dry-run-stable-60m-reversal-managed-return-observer",
      cwd: __dirname,
      script: "dist/src/cli/summarize-dry-run-returns.js",
      args: [
        "--reports-root",
        "var/paper-sessions-stable-60m-reversal-managed",
        "--cycles-path",
        "var/log/dry-run-stable-60m-reversal-managed-paper/cycles.ndjson",
        "--output",
        "var/reports/stable-60m-reversal-managed-paper-return-summary-latest.json",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-stable-60m-reversal-managed-return-observer.out.log",
      error_file: "./var/log/pm2/dry-run-stable-60m-reversal-managed-return-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-btc-240m-momentum-lb48-hold72-min150-range-p70-refresh-observer",
      cwd: __dirname,
      script: "dist/src/cli/refresh-bithumb-replacement-time-series-readiness.js",
      args: [
        "--scan",
        "var/reports/btc-240m-momentum-extended-threshold-fee50-official-rules-20260513.json",
        "--market",
        "KRW-BTC",
        "--signal-mode",
        "momentum",
        "--unit-minutes",
        "240",
        "--lookback-bars",
        "48",
        "--hold-bars",
        "72",
        "--min-return-bps",
        "150",
        "--risk-filter",
        "range24_below_p70",
        "--risk-threshold",
        "783.9218739484954",
        "--notional-krw",
        "500000",
        "--expected-median-edge-bps",
        "180.05636246",
        "--observation-output",
        "var/reports/btc-240m-momentum-lb48-hold72-min150-range-p70-forward-observation-latest.json",
        "--paper-observation-output",
        "var/reports/btc-240m-momentum-lb48-hold72-min150-range-p70-paper-observation-latest.json",
        "--position-audit-output",
        "var/reports/btc-240m-momentum-lb48-hold72-min150-range-p70-position-audit-latest.json",
        "--readiness-output",
        "var/reports/btc-240m-momentum-lb48-hold72-min150-range-p70-replacement-readiness-latest.json",
        "--paper-reports-dir",
        "var/paper-sessions-btc-240m-momentum-lb48-hold72-min150-range-p70-observation",
        "--strategy-id",
        "btc_240m_momentum_lb48_hold72_min150_range_p70_near_miss_v1",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-btc-240m-momentum-lb48-hold72-min150-range-p70-refresh-observer.out.log",
      error_file: "./var/log/pm2/dry-run-btc-240m-momentum-lb48-hold72-min150-range-p70-refresh-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-btc-240m-momentum-lb168-hold72-range-p70-managed-paper",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-btc-240m-momentum-lb168-hold72-range-p70-managed-paper.out.log",
      error_file: "./var/log/pm2/dry-run-btc-240m-momentum-lb168-hold72-range-p70-managed-paper.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
        DRY_RUN_EXECUTION_MODE: "paper",
        DRY_RUN_MARKETS: "KRW-BTC",
        DRY_RUN_ENTRY_PROFILE: "btc_240m_momentum_lb168_hold72_range_p70_candidate_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/dry-run-btc-240m-momentum-lb168-hold72-range-p70-managed-paper",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/paper-sessions-btc-240m-momentum-lb168-hold72-range-p70-managed",
      },
    },
    {
      name: "dry-run-btc-240m-momentum-lb168-hold72-range-p70-managed-return-observer",
      cwd: __dirname,
      script: "dist/src/cli/summarize-dry-run-returns.js",
      args: [
        "--reports-root",
        "var/paper-sessions-btc-240m-momentum-lb168-hold72-range-p70-managed",
        "--cycles-path",
        "var/log/dry-run-btc-240m-momentum-lb168-hold72-range-p70-managed-paper/cycles.ndjson",
        "--output",
        "var/reports/btc-240m-momentum-lb168-hold72-range-p70-managed-paper-return-summary-latest.json",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-btc-240m-momentum-lb168-hold72-range-p70-managed-return-observer.out.log",
      error_file: "./var/log/pm2/dry-run-btc-240m-momentum-lb168-hold72-range-p70-managed-return-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-pieverse-60m-reversal-lb168-managed-paper",
      cwd: __dirname,
      script: "dist/src/cli/run-dry-run-service.js",
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-pieverse-60m-reversal-lb168-managed-paper.out.log",
      error_file: "./var/log/pm2/dry-run-pieverse-60m-reversal-lb168-managed-paper.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
        DRY_RUN_EXECUTION_MODE: "paper",
        DRY_RUN_MARKETS: "KRW-PIEVERSE",
        DRY_RUN_ENTRY_PROFILE: "pieverse_60m_reversal_lb168_candidate_v1",
        DRY_RUN_EXIT_PROFILE: "balanced_v1",
        DRY_RUN_SYNTHETIC_EXIT_POLICY: "carry_open",
        DRY_RUN_LOOP_INTERVAL_SECONDS: "300",
        DRY_RUN_LOG_DIR: "var/log/dry-run-pieverse-60m-reversal-lb168-managed-paper",
        DRY_RUN_CYCLE_LOG_FILE: "cycles.ndjson",
        PAPER_SESSION_ARTIFACTS_DIR: "var/paper-sessions-pieverse-60m-reversal-lb168-managed",
      },
    },
    {
      name: "dry-run-pieverse-60m-reversal-lb168-managed-return-observer",
      cwd: __dirname,
      script: "dist/src/cli/summarize-dry-run-returns.js",
      args: [
        "--reports-root",
        "var/paper-sessions-pieverse-60m-reversal-lb168-managed",
        "--cycles-path",
        "var/log/dry-run-pieverse-60m-reversal-lb168-managed-paper/cycles.ndjson",
        "--output",
        "var/reports/pieverse-60m-reversal-lb168-managed-paper-return-summary-latest.json",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-pieverse-60m-reversal-lb168-managed-return-observer.out.log",
      error_file: "./var/log/pm2/dry-run-pieverse-60m-reversal-lb168-managed-return-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-pieverse-60m-reversal-lb168-refresh-observer",
      cwd: __dirname,
      script: "dist/src/cli/refresh-bithumb-replacement-time-series-readiness.js",
      args: [
        "--scan",
        "var/reports/krw-execution-candidates-49-60m-reversal-scan-fee35-500k-20260513.json",
        "--market",
        "KRW-PIEVERSE",
        "--signal-mode",
        "reversal",
        "--unit-minutes",
        "60",
        "--lookback-bars",
        "168",
        "--hold-bars",
        "24",
        "--min-return-bps",
        "50",
        "--min-drop-bps",
        "50",
        "--risk-filter",
        "rv24_below_median",
        "--risk-threshold",
        "751.7214747340527",
        "--notional-krw",
        "500000",
        "--expected-median-edge-bps",
        "129.95314",
        "--observation-output",
        "var/reports/pieverse-60m-reversal-lb168-rvmedian-forward-observation-latest.json",
        "--paper-observation-output",
        "var/reports/pieverse-60m-reversal-lb168-paper-observation-latest.json",
        "--position-audit-output",
        "var/reports/pieverse-60m-reversal-lb168-position-audit-latest.json",
        "--readiness-output",
        "var/reports/pieverse-60m-reversal-lb168-replacement-readiness-latest.json",
        "--paper-reports-dir",
        "var/paper-sessions-pieverse-60m-reversal-lb168-observation",
        "--strategy-id",
        "pieverse_60m_reversal_lb168_candidate_v1",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-pieverse-60m-reversal-lb168-refresh-observer.out.log",
      error_file: "./var/log/pm2/dry-run-pieverse-60m-reversal-lb168-refresh-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-top-funding-discovery-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--auto-top-funding-markets",
        "10",
        "--output",
        "var/reports/spot-perp-carry-top-funding-discovery-latest.json",
        "--min-observations",
        "1",
        "--min-completed-funding-events",
        "1",
        "--min-observation-span-minutes",
        "0",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-top-funding-discovery-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-top-funding-discovery-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-top-funding-fee-stress-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--auto-top-funding-markets",
        "20",
        "--output",
        "var/reports/spot-perp-carry-top-funding-discovery-25bps-current.json",
        "--bithumb-fee-bps",
        "25",
        "--binance-taker-fee-bps",
        "5",
        "--exit-cost-buffer-bps",
        "20",
        "--min-observations",
        "1",
        "--min-completed-funding-events",
        "1",
        "--min-observation-span-minutes",
        "0",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-top-funding-fee-stress-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-top-funding-fee-stress-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-current-carry-discovery-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--auto-top-current-carry-markets",
        "10",
        "--output",
        "var/reports/spot-perp-carry-current-carry-discovery-latest.json",
        "--min-observations",
        "1",
        "--min-completed-funding-events",
        "1",
        "--min-observation-span-minutes",
        "0",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-current-carry-discovery-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-current-carry-discovery-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-current-carry-fee-stress-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--auto-top-current-carry-markets",
        "20",
        "--output",
        "var/reports/spot-perp-carry-current-carry-discovery-25bps-current.json",
        "--bithumb-fee-bps",
        "25",
        "--binance-taker-fee-bps",
        "5",
        "--exit-cost-buffer-bps",
        "20",
        "--min-observations",
        "1",
        "--min-completed-funding-events",
        "1",
        "--min-observation-span-minutes",
        "0",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-current-carry-fee-stress-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-current-carry-fee-stress-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-72h-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--append-existing-output",
        "--output",
        "var/reports/spot-perp-carry-72h-latest.json",
        "--min-observations",
        "432",
        "--min-completed-funding-events",
        "6",
        "--min-observation-span-minutes",
        "4320",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-72h-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-72h-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-edu-72h-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--markets",
        "KRW-EDU:EDUUSDT",
        "--append-existing-output",
        "--output",
        "var/reports/spot-perp-carry-edu-72h-latest.json",
        "--min-observations",
        "432",
        "--min-completed-funding-events",
        "6",
        "--min-observation-span-minutes",
        "4320",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-edu-72h-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-edu-72h-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-edu-live-readiness-observer",
      cwd: __dirname,
      script: "npm",
      args: "run dry-run:refresh-spot-perp-carry-edu-live-readiness",
      interpreter: "none",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-edu-live-readiness-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-edu-live-readiness-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-cys-72h-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--markets",
        "KRW-CYS:CYSUSDT",
        "--append-existing-output",
        "--output",
        "var/reports/spot-perp-carry-cys-72h-latest.json",
        "--min-observations",
        "432",
        "--min-completed-funding-events",
        "6",
        "--min-observation-span-minutes",
        "4320",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-cys-72h-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-cys-72h-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-cys-live-readiness-observer",
      cwd: __dirname,
      script: "npm",
      args: "run dry-run:refresh-spot-perp-carry-cys-live-readiness",
      interpreter: "none",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-cys-live-readiness-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-cys-live-readiness-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-aztec-live-readiness-observer",
      cwd: __dirname,
      script: "npm",
      args: "run dry-run:refresh-spot-perp-carry-aztec-live-readiness",
      interpreter: "none",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-aztec-live-readiness-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-aztec-live-readiness-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-nil-live-readiness-observer",
      cwd: __dirname,
      script: "npm",
      args: "run dry-run:refresh-spot-perp-carry-nil-live-readiness",
      interpreter: "none",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-nil-live-readiness-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-nil-live-readiness-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-akt-live-readiness-observer",
      cwd: __dirname,
      script: "npm",
      args: "run dry-run:refresh-spot-perp-carry-akt-live-readiness",
      interpreter: "none",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-akt-live-readiness-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-akt-live-readiness-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-elsa-live-readiness-observer",
      cwd: __dirname,
      script: "npm",
      args: "run dry-run:refresh-spot-perp-carry-elsa-live-readiness",
      interpreter: "none",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-elsa-live-readiness-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-elsa-live-readiness-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-opportunity-72h-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--markets",
        "KRW-PIEVERSE:PIEVERSEUSDT,KRW-DEEP:DEEPUSDT,KRW-PARTI:PARTIUSDT,KRW-KITE:KITEUSDT,KRW-METIS:METISUSDT,KRW-MOVE:MOVEUSDT,KRW-NIL:NILUSDT,KRW-BSV:BSVUSDT,KRW-BABY:BABYUSDT,KRW-EDEN:EDENUSDT,KRW-SXT:SXTUSDT,KRW-LIT:LITUSDT,KRW-MON:MONUSDT,KRW-MOCA:MOCAUSDT,KRW-MERL:MERLUSDT,KRW-ILV:ILVUSDT,KRW-AZTEC:AZTECUSDT,KRW-TIA:TIAUSDT,KRW-PRL:PRLUSDT,KRW-FRAX:FRAXUSDT,KRW-ZK:ZKUSDT,KRW-D:DUSDT,KRW-H:HUSDT,KRW-HEMI:HEMIUSDT,KRW-SAHARA:SAHARAUSDT,KRW-IN:INUSDT,KRW-XAN:XANUSDT,KRW-ICP:ICPUSDT,KRW-ORCA:ORCAUSDT,KRW-RECALL:RECALLUSDT,KRW-CYS:CYSUSDT,KRW-PROMPT:PROMPTUSDT,KRW-SONIC:SONICUSDT,KRW-VVV:VVVUSDT,KRW-EDU:EDUUSDT,KRW-API3:API3USDT,KRW-AKT:AKTUSDT,KRW-ACX:ACXUSDT,KRW-ARPA:ARPAUSDT,KRW-POLYX:POLYXUSDT,KRW-ETHFI:ETHFIUSDT,KRW-TOSHI:TOSHIUSDT,KRW-STABLE:STABLEUSDT,KRW-SCR:SCRUSDT,KRW-CVC:CVCUSDT,KRW-BTR:BTRUSDT,KRW-EUL:EULUSDT,KRW-XVS:XVSUSDT,KRW-G:GUSDT,KRW-ELSA:ELSAUSDT,KRW-GPS:GPSUSDT,KRW-RPL:RPLUSDT",
        "--append-existing-output",
        "--filter-input-to-markets",
        "--output",
        "var/reports/spot-perp-carry-opportunity-72h-latest.json",
        "--min-observations",
        "432",
        "--min-completed-funding-events",
        "6",
        "--min-observation-span-minutes",
        "4320",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "512M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-opportunity-72h-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-opportunity-72h-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-pieverse-edu-72h-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--markets",
        "KRW-PIEVERSE:PIEVERSEUSDT,KRW-EDU:EDUUSDT",
        "--append-existing-output",
        "--output",
        "var/reports/spot-perp-carry-pieverse-edu-72h-latest.json",
        "--min-observations",
        "432",
        "--min-completed-funding-events",
        "6",
        "--min-observation-span-minutes",
        "4320",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-pieverse-edu-72h-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-pieverse-edu-72h-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-pieverse-edu-live-readiness-observer",
      cwd: __dirname,
      script: "npm",
      args: "run dry-run:refresh-spot-perp-carry-pieverse-edu-live-readiness",
      interpreter: "none",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file:
        "./var/log/pm2/dry-run-spot-perp-carry-pieverse-edu-live-readiness-observer.out.log",
      error_file:
        "./var/log/pm2/dry-run-spot-perp-carry-pieverse-edu-live-readiness-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-pieverse-72h-observer",
      cwd: __dirname,
      script: "dist/src/cli/analyze-spot-perp-carry.js",
      args: [
        "--markets",
        "KRW-PIEVERSE:PIEVERSEUSDT",
        "--append-existing-output",
        "--output",
        "var/reports/spot-perp-carry-pieverse-72h-latest.json",
        "--min-observations",
        "432",
        "--min-completed-funding-events",
        "6",
        "--min-observation-span-minutes",
        "4320",
        "--min-net-carry-bps",
        "10",
        "--min-positive-carry-rate",
        "0.67",
        "--min-depth-coverage-rate",
        "0.95",
        "--quiet",
      ].join(" "),
      interpreter: "node",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-spot-perp-carry-pieverse-72h-observer.out.log",
      error_file: "./var/log/pm2/dry-run-spot-perp-carry-pieverse-72h-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-spot-perp-carry-pieverse-live-readiness-observer",
      cwd: __dirname,
      script: "npm",
      args: "run dry-run:refresh-spot-perp-carry-pieverse-live-readiness",
      interpreter: "none",
      autorestart: true,
      restart_delay: 300000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file:
        "./var/log/pm2/dry-run-spot-perp-carry-pieverse-live-readiness-observer.out.log",
      error_file:
        "./var/log/pm2/dry-run-spot-perp-carry-pieverse-live-readiness-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
    {
      name: "dry-run-live-goal-status-observer",
      cwd: __dirname,
      script: "npm",
      args: "run dry-run:refresh-live-goal-status-if-due",
      interpreter: "none",
      autorestart: true,
      restart_delay: 600000,
      kill_timeout: 10000,
      max_memory_restart: "256M",
      merge_logs: true,
      time: true,
      out_file: "./var/log/pm2/dry-run-live-goal-status-observer.out.log",
      error_file: "./var/log/pm2/dry-run-live-goal-status-observer.err.log",
      env: {
        TRADING_MODE: "paper",
        ENABLE_LIVE_EXECUTION: "false",
      },
    },
  ],
};
